require('core.plugins')
require('core.mappings')
require('core.configs')
require('core.theme')

require('plugins.neotree')
require('plugins.treesitter')
require('plugins.lsp')
require('plugins.mason')
require('plugins.nullls')
require('plugins.bufferline')
require('plugins.lualine')
require('plugins.toggleterm')
require('plugins.treesittercontext')

